# Generated by Django 5.0.9 on 2026-09-20 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_product_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=600)),
                ('image_url', models.URLField(blank=True, default='', max_length=600)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('preferred_strategy', models.CharField(choices=[('json_api', 'Cached JSON endpoint'), ('http_html', 'HTTP + HTML parse'), ('browser', 'Headless browser')], default='json_api', max_length=20)),
                ('dom_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('interval_minutes', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_in_stock', models.BooleanField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('cron', 'Cron'), ('manual', 'Manual'), ('headed', 'Headed')], default='cron', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('products_attempted', models.PositiveIntegerField(default=0)),
                ('products_succeeded', models.PositiveIntegerField(default=0)),
                ('products_failed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=64, unique=True)),
                ('list_endpoint', models.CharField(blank=True, default='', max_length=500)),
                ('detail_endpoint_template', models.CharField(blank=True, default='', max_length=500)),
                ('json_shape', models.JSONField(blank=True, default=dict)),
                ('dom_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('in_stock', models.BooleanField(blank=True, null=True)),
                ('stock_text', models.CharField(blank=True, default='', max_length=120)),
                ('strategy', models.CharField(default='', max_length=20)),
                ('scraped_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='tracker.product')),
            ],
            options={
                'ordering': ['scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('price_drop', 'Price drop'), ('price_rise', 'Price rise'), ('back_in_stock', 'Back in stock'), ('out_of_stock', 'Out of stock'), ('structure_change', 'Page structure changed'), ('scraper_unhealthy', 'Scraper unhealthy')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracker.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('retried', 'Succeeded after retry'), ('failed', 'Failed'), ('rejected', 'Rejected by validation')], db_index=True, max_length=20)),
                ('strategy', models.CharField(blank=True, default='', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('price_found', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('in_stock_found', models.BooleanField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('trace', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tracker.product')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='tracker.scraperun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
